### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by gritfessel** [hpi-swa-teaching/ChangesBrowser#91]
Currently, our tests are outdated because we changed our architecture. So we have to write new tests

**Checklist**

- [ ] #52 Show changes made to method over time
- [ ] #56 Be able to switch between both views
- [ ] #46 Add changes in list
- [ ] #47 Make changes selectable
- [ ] #48 Make change selection invertable

**Comment by SilvanVerhoeven** [comment]
So, we basically implemented ALL tests, except the one that is requested in this issue. Grit and I are still proud of ourselves.
